version: '3'  # version of compose format 

services:
  api-service:
    build: ./api
    volumes:
      - ./api:/usr/src/app 
    ports:
      - 5000:5000  # host:container

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5001:80  # host:container
    depends_on:
      - api-service # website is not going to work unless laptop-service is running
    links:
      - db

  db:
    image: mongo:3.0.2
